version: '3.7'

services:
  app:
    build: ./music_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./music_project/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=dev_db

volumes:
  postgres_data:
