version: '3.7'

services:
  app:
    build: ./music_project
    command: gunicorn --bind 0.0.0.0:8000 music_project.wsgi:application
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume:
  media_volume: