# Generated by Django 4.0.1 on 2022-01-31 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_api', '0002_alter_album_cover_alter_track_cover_alter_track_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(to='music_api.Genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(to='music_api.Genre'),
        ),
    ]
