# Generated by Django 4.0.1 on 2022-01-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_api', '0003_alter_album_authors_alter_album_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
